services:
  ai-service:
    build: ./services/ai-service
    container_name: ai-service
    networks:
      vu-net:

  backend:
    build: ./services/backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - ai-service
    networks:
      vu-net:

networks:
  vu-net:
    driver: bridge
